name: feelTheField-CondaEnv
channels:
    - conda-forge
    - anaconda
    - defaults
dependencies:
    - alabaster = 0.7.12
    - alembic = 1.8.1
    - antlr-python-runtime = 4.9.3
    - anyio = 3.5.0
    - aom = 3.5.0
    - appdirs = 1.4.4
    - appnope = 0.1.3
    - argon2-cffi = 21.3.0
    - argon2-cffi-bindings = 21.2.0
    - asttokens = 2.1.0
    - attrs = 21.4.0
    - audioread = 3.0.0
    - babel = 2.10.1
    - backcall = 0.2.0
    - backports = 1.0
    - backports.functools_lru_cache = 1.6.4
    - bcrypt = 3.2.2
    - beautifulsoup4 = 4.11.1
    - bleach = 5.0.0
    - blinker = 1.5
    - brotli = 1.0.9
    - brotli-bin = 1.0.9
    - brotlipy = 0.7.0
    - bzip2 = 1.0.8
    - c-ares = 1.18.1
    - ca-certificates = 2022.9.24
    - cctools = 973.0.1
    - cctools_osx-arm64 = 973.0.1
    - certifi = 2022.9.24
    - cffi = 1.15.0
    - chardet = 4.0.0
    - charset-normalizer = 2.0.12
    - click = 8.1.3
    - cloudpickle = 2.2.0
    - colorama = 0.4.6
    - conda = 22.9.0
    - conda-build = 3.22.0
    - conda-package-handling = 1.9.0
    - configparser = 5.3.0
    - contourpy = 1.0.6
    - coverage = 6.5.0
    - cryptography = 38.0.3
    - curl = 7.86.0
    - cycler = 0.10.0
    - databricks-cli = 0.17.3
    - debugpy = 1.6.3
    - decorator = 5.1.1
    - defusedxml = 0.7.1
    - distlib = 0.3.4
    - docker-py = 6.0.0
    - docutils = 0.19
    - dtw-python = 1.3.0
    - entrypoints = 0.4
    - executing = 1.2.0
    - expat = 2.5.0
    - fastdtw = 0.3.4
    - ffmpeg = 5.1.2
    - filelock = 3.6.0
    - flake8 = 4.0.1
    - flask = 2.2.2
    - flit-core = 3.8.0
    - font-ttf-dejavu-sans-mono = 2.37
    - font-ttf-inconsolata = 3.000
    - font-ttf-source-code-pro = 2.038
    - font-ttf-ubuntu = 0.83
    - fontconfig = 2.14.1
    - fonts-conda-ecosystem = 1
    - fonts-conda-forge = 1
    - fonttools = 4.38.0
    - freetype = 2.12.1
    - gettext = 0.21.1
    - git = 2.38.1
    - git-filter-repo = 2.34.0
    - gitdb = 4.0.9
    - gitpython = 3.1.29
    - glob2 = 0.7
    - gmp = 6.2.1
    - gnutls = 3.7.8
    - greenlet = 2.0.1
    - gunicorn = 20.1.0
    - h5py = 3.6.0
    - hdf5 = 1.12.1
    - hydra-core = 1.2.0
    - icu = 70.1
    - idna = 3.4
    - imagesize = 1.4.1
    - importlib-metadata = 4.11.3
    - importlib-resources = 5.7.1
    - importlib_metadata = 4.11.3
    - importlib_resources = 5.7.1
    - iniconfig = 1.1.1
    - ipykernel = 6.17.1
    - ipython = 8.6.0
    - ipython_genutils = 0.2.0
    - ipywidgets = 8.0.2
    - isort = 5.7.0
    - itsdangerous = 2.1.2
    - jedi = 0.18.1
    - jinja2 = 3.1.2
    - joblib = 1.0.0
    - jpeg = 9e
    - jsonpickle = 2.2.0
    - jsonschema = 4.4.0
    - jupyter = 1.0.0
    - jupyter_client = 7.4.7
    - jupyter_console = 6.4.4
    - jupyter_core = 5.0.0
    - jupyter_server = 1.23.2
    - jupyterlab_pygments = 0.2.2
    - jupyterlab_widgets = 3.0.3
    - krb5 = 1.19.3
    - lame = 3.100
    - lcms2 = 2.14
    - ld64 = 609
    - ld64_osx-arm64 = 609
    - lerc = 4.0.0
    - libarchive = 3.6.1
    - libblas = 3.9.0
    - libbrotlicommon = 1.0.9
    - libbrotlidec = 1.0.9
    - libbrotlienc = 1.0.9
    - libcblas = 3.9.0
    - libcurl = 7.86.0
    - libcxx = 14.0.6
    - libdeflate = 1.14
    - libedit = 3.1.20191231
    - libev = 4.33
    - libffi = 3.4.2
    - libflac = 1.4.2
    - libgfortran = 5.0.0
    - libgfortran5 = 11.3.0
    - libiconv = 1.17
    - libidn2 = 2.3.4
    - liblapack = 3.9.0
    - liblief = 0.12.3
    - libllvm11 = 11.1.0
    - libnghttp2 = 1.47.0
    - libogg = 1.3.4
    - libopenblas = 0.3.21
    - libopus = 1.3.1
    - libpng = 1.6.38
    - libprotobuf = 3.21.9
    - librosa = 0.9.2
    - libsndfile = 1.1.0
    - libsodium = 1.0.18
    - libsqlite = 3.39.4
    - libssh2 = 1.10.0
    - libtasn1 = 4.19.0
    - libtiff = 4.4.0
    - libunistring = 0.9.10
    - libvorbis = 1.3.7
    - libvpx = 1.11.0
    - libwebp-base = 1.2.4
    - libxcb = 1.13
    - libxml2 = 2.10.3
    - libzlib = 1.2.13
    - llvm-openmp = 15.0.5
    - llvmlite = 0.39.1
    - lz4-c = 1.9.3
    - lzo = 2.10
    - mako = 1.2.4
    - markupsafe = 2.1.1
    - matplotlib-base = 3.6.2
    - matplotlib-inline = 0.1.6
    - mccabe = 0.6.1
    - mistune = 2.0.4
    - mlflow = 1.30.0
    - more-itertools = 8.6.0
    - mpg123 = 1.30.2
    - munkres = 1.1.4
    - music21 = 6.5.0
    - nbclassic = 0.4.8
    - nbconvert-core = 7.2.5
    - nbconvert-pandoc = 7.2.5
    - nbformat = 5.3.0
    - ncurses = 6.3
    - nest-asyncio = 1.5.6
    - nettle = 3.8.1
    - notebook = 6.5.2
    - notebook-shim = 0.2.2
    - numba = 0.56.3
    - numpy = 1.23.3
    - oauthlib = 3.2.2
    - omegaconf = 2.2.3
    - openh264 = 2.3.1
    - openjpeg = 2.5.0
    - openssl = 3.0.7
    - p11-kit = 0.24.1
    - packaging = 21.3
    - pandas = 1.4.2
    - pandoc = 2.19.2
    - pandocfilters = 1.5.0
    - paramiko = 2.12.0
    - parso = 0.8.3
    - patch = 2.7.6
    - patsy = 0.5.3
    - pcre2 = 10.40
    - perl = 5.32.1
    - pexpect = 4.8.0
    - pickleshare = 0.7.5
    - pip = 22.3.1
    - pkginfo = 1.8.3
    - platformdirs = 2.5.2
    - pluggy = 1.0.0
    - pooch = 1.6.0
    - prometheus_client = 0.15.0
    - prometheus_flask_exporter = 0.21.0
    - prompt-toolkit = 3.0.32
    - prompt_toolkit = 3.0.32
    - protobuf = 4.21.9
    - psutil = 5.9.4
    - pthread-stubs = 0.4
    - ptyprocess = 0.7.0
    - pure_eval = 0.2.2
    - py = 1.11.0
    - py-lief = 0.12.3
    - pycodestyle = 2.8.0
    - pycosat = 0.6.4
    - pycparser = 2.21
    - pyflakes = 2.4.0
    - pygments = 2.13.0
    - pyjwt = 2.6.0
    - pynacl = 1.5.0
    - pyopenssl = 22.1.0
    - pyparsing = 3.0.9
    - pyrsistent = 0.19.2
    - pysocks = 1.7.1
    - pysoundfile = 0.11.0
    - pytest = 7.1.2
    - python = 3.10.6
    - python-dateutil = 2.8.2
    - python-dotenv = 0.21.0
    - python-fastjsonschema = 2.16.2
    - python-libarchive-c = 4.0
    - python_abi = 3.10
    - pytz = 2022.6
    - pywin32-on-windows = 0.1.0
    - pyyaml = 6.0
    - pyzmq = 24.0.1
    - querystring_parser = 1.2.4
    - readline = 8.1.2
    - requests = 2.27.1
    - resampy = 0.4.2
    - retry = 0.9.2
    - ripgrep = 13.0.0
    - ruamel_yaml = 0.15.80
    - scikit-learn = 1.0.2
    - scipy = 1.9.3
    - seaborn = 0.12.0
    - seaborn-base = 0.12.0
    - send2trash = 1.8.0
    - setuptools = 65.5.1
    - sigtool = 0.1.3
    - six = 1.16.0
    - smmap = 3.0.5
    - sniffio = 1.3.0
    - snowballstemmer = 2.2.0
    - soupsieve = 2.3.2.post1
    - sphinx = 5.3.0
    - sphinxcontrib-applehelp = 1.0.2
    - sphinxcontrib-devhelp = 1.0.2
    - sphinxcontrib-htmlhelp = 2.0.0
    - sphinxcontrib-jsmath = 1.0.1
    - sphinxcontrib-qthelp = 1.0.3
    - sphinxcontrib-serializinghtml = 1.1.5
    - sqlalchemy = 1.4.44
    - sqlparse = 0.4.3
    - stack_data = 0.6.1
    - statsmodels = 0.13.5
    - svt-av1 = 1.3.0
    - tabulate = 0.9.0
    - tapi = 1100.0.11
    - terminado = 0.13.3
    - threadpoolctl = 3.1.0
    - tinycss2 = 1.1.1
    - tk = 8.6.12
    - toml = 0.10.2
    - tomli = 2.0.1
    - toolz = 0.12.0
    - tornado = 6.2
    - tqdm = 4.64.1
    - traitlets = 5.5.0
    - typing_extensions = 4.4.0
    - tzdata = 2022f
    - unicodedata2 = 15.0.0
    - urllib3 = 1.26.9
    - virtualenv = 20.14.1
    - wcwidth = 0.2.5
    - webcolors = 1.11.1
    - webencodings = 0.5.1
    - websocket-client = 1.3.2
    - werkzeug = 2.2.2
    - wheel = 0.38.4
    - widgetsnbextension = 4.0.3
    - x264 = 1!164.3095
    - x265 = 3.5
    - xorg-libxau = 1.0.9
    - xorg-libxdmcp = 1.1.3
    - xz = 5.2.6
    - yaml = 0.2.5
    - zeromq = 4.3.4
    - zipp = 3.10.0
    - zlib = 1.2.13
    - zstd = 1.5.2
    - pip:
        - astroid == 2.4.2
        - cython == 0.29.32
        - fastjsonschema == 2.15.3
        - imageio == 2.22.4
        - ipython-genutils == 0.2.0
        - japanize-matplotlib == 1.1.3
        - json5 == 0.9.6
        - jupyter-client == 7.3.0
        - jupyter-core == 4.10.0
        - jupyter-server == 1.17.0
        - jupyterlab-server == 2.13.0
        - kiwisolver == 1.3.1
        - lazy-object-proxy == 1.4.3
        - matplotlib == 3.3.4
        - mglearn == 0.1.9
        - nbclient == 0.6.6
        - nbconvert == 6.5.0
        - pillow == 8.1.0
        - pylint == 2.6.0
        - stack-data == 0.2.0
        - tslearn == 0.5.2
        - tssearch == 0.1.3
        - wrapt == 1.12.1
